language: php

php:
  - 7.1
  - 7.2

env:
  matrix:
    - DEPENDENCIES="high"
    - DEPENDENCIES="low"

before_script:
  - if [ "$DEPENDENCIES" = "high" ]; then composer --prefer-source update; fi;
  - if [ "$DEPENDENCIES" = "low" ]; then composer --prefer-lowest --prefer-source update; fi;

script:
  - ./vendor/bin/phpunit --coverage-clover ./build/logs/clover.xml --exclude-group Functional
  - ./vendor/bin/phpunit --group=Functional
  - php -n ./vendor/bin/phpbench run --report=aggregate --revs=500 --iterations=50 --warmup=3
  # Only run the code standards with the latest package
  - if [ "$DEPENDENCIES" = "high" ]; then ./vendor/bin/phpcs --standard=PSR2 ./src/ ./tests/ ./benchmarks; fi;

after_script:
  - if [[ $TRAVIS_PHP_VERSION = '7.1' ]]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [[ $TRAVIS_PHP_VERSION = '7.1' ]]; then php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml; fi
